### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by evbogue** [evbogue/decent#11]
Someone should really fix this. It has to do with adding headers to the Decent fork of `ssb-ws` after the headers have already been set.

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at /home/ev/minbase/node_modules/decent-ssb/plugins/ws/json-api.js:23:11
    at handle (/home/ev/minbase/node_modules/stack/stack.js:11:9)
    at /home/ev/minbase/node_modules/stack/stack.js:13:11
    at /home/ev/minbase/node_modules/emoji-server/index.js:21:7
    at handle (/home/ev/minbase/node_modules/stack/stack.js:11:9)
    at /home/ev/minbase/node_modules/stack/stack.js:13:11
    at /home/ev/minbase/bin.js:48:16
    at /home/ev/minbase/node_modules/decent-ssb/plugins/ws/json-api.js:18:40
```

That someone is probably me.

**Comment by evbogue** [comment]
Fixed in 645217d99c57cf97d45d14bceb62bf988559caed by depending on http://github.com/evbogue/decent-ws/
