### ISSUE TITLE
invites are not working

### ISSUE THREAD

**Issue by evbogue** [evbogue/decent#9]
For some reason invites aren't working anymore in the latest version of Decent. I'm not sure if I broke this, or a dependency?

```

/home/ev/decent/node_modules/muxrpcli/index.js:68
      throw err
      ^
Error: method:invite,create is not on whitelist
    at Function.perms.pre (/home/ev/decent/node_modules/muxrpc/permissions.js:88:14)
    at Object.<anonymous> (/home/ev/decent/node_modules/muxrpc/local-api.js:35:21)
    at Object.request (/home/ev/decent/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/home/ev/decent/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/home/ev/decent/node_modules/packet-stream/index.js:134:41)
    at /home/ev/decent/node_modules/muxrpc/pull-weird.js:56:15
    at /home/ev/decent/node_modules/pull-stream/sinks/drain.js:24:37
    at /home/ev/decent/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/home/ev/decent/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/home/ev/decent/node_modules/pull-reader/index.js:39:14)
```

**Comment by evbogue** [comment]
I had the `master` plugin disabled, and it's required to be able to create invites.
